-- MySQL Script generated by MySQL Workbench
-- Fri Jan 30 17:32:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `nome_da_empresa` VARCHAR(180) NULL,
  `cnpj` VARCHAR(18) NULL,
  `quantidade_de_funcionarios` INT NULL,
  `data_de_cadastro` DATETIME NULL,
  PRIMARY KEY (`idEmpresa`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(180) NULL,
  `email` VARCHAR(180) NULL,
  `senha` VARCHAR(255) NULL,
  `data_de_criacao` DATETIME NULL,
  `idEmpresa` INT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `idEmpresa_idx` (`idEmpresa` ASC) INVISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  CONSTRAINT `idEmpresa`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `new_schema1`.`Empresa` (`idEmpresa`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Usuario_Comum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Usuario_Comum` (
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `new_schema1`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Admin_do_Sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Admin_do_Sistema` (
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `new_schema1`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Admin_da_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Admin_da_Empresa` (
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `idUsuario00`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `new_schema1`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Integracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Integracao` (
  `idIntegracao` INT NOT NULL,
  `chave_api` VARCHAR(180) NULL,
  `tipo_de_integracao` VARCHAR(45) NULL,
  `idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idIntegracao`),
  CONSTRAINT `idEmpresa`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `new_schema1`.`Empresa` (`idEmpresa`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `valor` DECIMAL NULL,
  `data_de_pagamento` DATETIME NULL,
  `tipo_de_pagamento` VARCHAR(45) NULL,
  `idEmpresa` INT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `idEmpresa0_idx` (`idEmpresa` ASC) VISIBLE,
  CONSTRAINT `idEmpresa0`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `new_schema1`.`Empresa` (`idEmpresa`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Log_de_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Log_de_acesso` (
  `id_log` INT NOT NULL,
  `ip` VARCHAR(180) NULL,
  `data_hora` DATETIME NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`id_log`),
  INDEX `idUsuario0_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idUsuario0`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `new_schema1`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Credito` (
  `idCredito` INT NOT NULL,
  `quantidade` INT NULL,
  `data_de_validade` DATETIME NULL,
  `idEmpresa` INT NULL,
  PRIMARY KEY (`idCredito`),
  INDEX `idEmpresa1_idx` (`idEmpresa` ASC) VISIBLE,
  CONSTRAINT `idEmpresa1`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `new_schema1`.`Empresa` (`idEmpresa`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Pesquisa` (
  `idPesquisa` INT NOT NULL,
  `data_de_pesquisa` DATETIME NULL,
  `termo_de_busca` VARCHAR(80) NULL,
  `quantidade_de_leads` INT NULL,
  `idUsuario` INT NULL,
  `idCredito` INT NULL,
  PRIMARY KEY (`idPesquisa`),
  INDEX `idUsuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `idCredito0_idx` (`idCredito` ASC) VISIBLE,
  CONSTRAINT `idUsuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `new_schema1`.`Usuario_Comum` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCredito0`
    FOREIGN KEY (`idCredito`)
    REFERENCES `new_schema1`.`Credito` (`idCredito`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Lead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Lead` (
  `idLead` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereco` VARCHAR(100) NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `CEP` VARCHAR(45) NULL,
  `Rua` VARCHAR(18) NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLead`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Resultado_de_pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Resultado_de_pesquisa` (
  `idPesquisa` INT NOT NULL,
  `data_de_associacao` DATETIME NULL,
  `ordem` VARCHAR(45) NULL,
  `relevancia` VARCHAR(45) NULL,
  `idLead` INT NOT NULL,
  PRIMARY KEY (`idPesquisa`, `idLead`),
  INDEX `idLead_idx` (`idLead` ASC) VISIBLE,
  CONSTRAINT `idPesquisa`
    FOREIGN KEY (`idPesquisa`)
    REFERENCES `new_schema1`.`Pesquisa` (`idPesquisa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLead`
    FOREIGN KEY (`idLead`)
    REFERENCES `new_schema1`.`Lead` (`idLead`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
